# Generated by Django 5.1.4 on 2025-02-06 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_chef', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Store_Admin.customuser',),
        ),
        migrations.CreateModel(
            name='ShopManagerUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_shop_manager', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Store_Admin.customuser',),
        ),
        migrations.CreateModel(
            name='ShopOwnerUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_shop_owner', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Store_Admin.customuser',),
        ),
    ]
