# Generated by Django 5.1.4 on 2025-02-12 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_Admin', '0004_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Store_Admin.cafe'),
        ),
    ]
