# Generated by Django 5.1.4 on 2025-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_Admin', '0006_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
